version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            pytest

  plan_deploy:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Terraform Init and Plan
          command: |
            cd terraform
            terraform init
            terraform plan -out=tfplan
      - run:
          name: Terraform Apply
          command: |
            cd terraform
            terraform apply -input=false tfplan

workflows:
  version: 2
  test_deploy:
    jobs:
      - build
      - plan_deploy:
          requires:
            - build

